### ISSUE TITLE
Server crash when placing rainbow bed

### ISSUE THREAD

**Issue by c01dc0ffee** [Wolren/PrideLand#2]
Hi, thank you for the wonderful mod.

I'm encountering a crash when hosting this mod on a server as soon as the rainbow bed is placed or loaded.

I have attached the relevant crash log.
[crash-2024-06-03_20.27.04-server.txt](https://github.com/user-attachments/files/15539427/crash-2024-06-03_20.27.04-server.txt)

**Comment by BorretSquared** [comment]
this issue is still relevant
